### ISSUE TITLE
ModuleNotFoundError: No module named 'html2safehtml'

### ISSUE THREAD

**Issue by jeroenst** [randombit/grab-rss#1]
Hi!

I try to use your code but I get the error 'ModuleNotFoundError: No module named 'html2safehtml''' when running your code. 

```
root@server:/opt/grab-rss# python3 ./grab_rss
Traceback (most recent call last):
  File "./grab_rss", line 21, in <module>
    import stripogram
  File "/usr/local/lib/python3.8/dist-packages/stripogram/__init__.py", line 10, in <module>
    from html2safehtml import HTML2SafeHTML
ModuleNotFoundError: No module named 'html2safehtml'
```

Stripogram is installed:

```
root@server:/opt/grab-rss# pip3.8 install stripogram
Requirement already satisfied: stripogram in /usr/local/lib/python3.8/dist-packages (1.5)
```

How can I solve this issue?

**Comment by jeroenst** [comment]
Switched to https://github.com/rss2email/rss2email
